apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: prepchef
    environment: {{ .Values.global.environment }}
data:
  nodeEnv: {{ .Values.config.nodeEnv | quote }}
  logLevel: {{ .Values.config.logLevel | quote }}
  stripeWebhookPath: {{ .Values.config.stripeWebhookPath | quote }}
  postgresHost: {{ .Values.postgres.host | quote }}
  postgresPort: {{ .Values.postgres.port | quote }}
  postgresDatabase: {{ .Values.postgres.database | quote }}
  redisHost: {{ .Values.redis.host | quote }}
  redisPort: {{ .Values.redis.port | quote }}
  minioEndpoint: {{ .Values.minio.endpoint | quote }}
