{{- if .Values.complianceReports.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "prepchef.fullname" . }}-compliance-reports
  labels:
    app.kubernetes.io/name: {{ include "prepchef.name" . }}
    app.kubernetes.io/component: compliance-reports
    {{- include "prepchef.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.complianceReports.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "prepchef.name" . }}
            app.kubernetes.io/component: compliance-reports
        spec:
          serviceAccountName: {{ include "prepchef.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
            - name: compliance-reports
              image: "{{ .Values.complianceReports.image.repository }}:{{ .Values.complianceReports.image.tag }}"
              imagePullPolicy: {{ .Values.complianceReports.image.pullPolicy }}
              env:
{{- range .Values.complianceReports.env }}
                - name: {{ .name }}
{{- if .value }}
                  value: {{ .value | quote }}
{{- end }}
{{- if .valueFrom }}
                  valueFrom:
{{ toYaml .valueFrom | indent 20 }}
{{- end }}
{{- end }}
              resources:
{{ toYaml .Values.complianceReports.resources | indent 16 }}
{{- end }}
