---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeApi.name }}
  labels:
    app: prepchef
    component: {{ .Values.nodeApi.name }}
spec:
  type: {{ .Values.nodeApi.service.type }}
  ports:
    - port: {{ .Values.nodeApi.service.port }}
      targetPort: {{ .Values.nodeApi.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: prepchef
    component: {{ .Values.nodeApi.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pythonCompliance.name }}
  labels:
    app: prepchef
    component: {{ .Values.pythonCompliance.name }}
spec:
  type: {{ .Values.pythonCompliance.service.type }}
  ports:
    - port: {{ .Values.pythonCompliance.service.port }}
      targetPort: {{ .Values.pythonCompliance.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: prepchef
    component: {{ .Values.pythonCompliance.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: prepchef
    component: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: prepchef
    component: {{ .Values.frontend.name }}
