openapi: 3.0.3
info:
  title: Routing Service API
  version: "1.0.0"
paths:
  /route/query:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                zip:
                  type: string
      responses:
        "200":
          description: routing decision
          content:
            application/json:
              schema:
                type: object
                properties:
                  provider:
                    type: string
                    enum: [UBER_DIRECT, DOORDASH_DRIVE, POSTMATES]
                  score:
                    type: number
                  ttl_sec:
                    type: integer
