# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from http import HTTPStatus
from typing import Any, Dict, Union

import httpx

from ...client import Client
from ...models.requirement_estimate_request import RequirementEstimateRequest
from ...models.requirement_estimate_response import RequirementEstimateResponse
from ...types import UNSET, Response, Unset, UnexpectedStatus


def _get_kwargs(
    *,
    client: Client,
    json_body: RequirementEstimateRequest,
    idempotency_key: Union[Unset, str] = UNSET,
    prep_version: Union[Unset, str] = UNSET,
) -> Dict[str, Any]:
    headers = client.get_headers()
    if not isinstance(idempotency_key, Unset) and idempotency_key is not UNSET:
        headers["Idempotency-Key"] = idempotency_key
    if not isinstance(prep_version, Unset) and prep_version is not UNSET:
        headers["Prep-Version"] = prep_version

    json_json_body = json_body.model_dump(by_alias=True, exclude_none=True)

    return {
        "method": "post",
        "url": "/requirements/estimate",
        "headers": headers,
        "cookies": client.get_cookies(),
        "timeout": client.get_timeout(),
        "json": json_json_body,
    }


def _parse_response(*, client: Client, response: httpx.Response) -> Optional[RequirementEstimateResponse]:
    if response.status_code == HTTPStatus.OK:
        return RequirementEstimateResponse.model_validate(response.json())
    if client.raise_on_unexpected_status:
        raise UnexpectedStatus(response.status_code, response.content)
    return None


def _build_response(*, client: Client, response: httpx.Response) -> Response[RequirementEstimateResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=dict(response.headers),
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: Client,
    json_body: RequirementEstimateRequest,
    idempotency_key: Union[Unset, str] = UNSET,
    prep_version: Union[Unset, str] = UNSET,
) -> Response[RequirementEstimateResponse]:
    """Estimate the filings and fees required for a business scenario."""

    kwargs = _get_kwargs(
        client=client,
        json_body=json_body,
        idempotency_key=idempotency_key,
        prep_version=prep_version,
    )

    with httpx.Client(
        base_url=client.base_url,
        verify=client.verify_ssl,
        follow_redirects=client.follow_redirects,
    ) as _client:
        response = _client.request(**kwargs)

    return _build_response(client=client, response=response)


def sync(
    *,
    client: Client,
    json_body: RequirementEstimateRequest,
    idempotency_key: Union[Unset, str] = UNSET,
    prep_version: Union[Unset, str] = UNSET,
) -> Optional[RequirementEstimateResponse]:
    """Estimate the filings and fees required for a business scenario."""

    return sync_detailed(
        client=client,
        json_body=json_body,
        idempotency_key=idempotency_key,
        prep_version=prep_version,
    ).parsed


async def asyncio_detailed(
    *,
    client: Client,
    json_body: RequirementEstimateRequest,
    idempotency_key: Union[Unset, str] = UNSET,
    prep_version: Union[Unset, str] = UNSET,
) -> Response[RequirementEstimateResponse]:
    """Estimate the filings and fees required for a business scenario."""

    kwargs = _get_kwargs(
        client=client,
        json_body=json_body,
        idempotency_key=idempotency_key,
        prep_version=prep_version,
    )

    async with httpx.AsyncClient(
        base_url=client.base_url,
        verify=client.verify_ssl,
        follow_redirects=client.follow_redirects,
    ) as _client:
        response = await _client.request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: Client,
    json_body: RequirementEstimateRequest,
    idempotency_key: Union[Unset, str] = UNSET,
    prep_version: Union[Unset, str] = UNSET,
) -> Optional[RequirementEstimateResponse]:
    """Estimate the filings and fees required for a business scenario."""

    return (
        await asyncio_detailed(
            client=client,
            json_body=json_body,
            idempotency_key=idempotency_key,
            prep_version=prep_version,
        )
    ).parsed
