openapi: 3.1.0
info:
  title: PrepChef Food Inspection API
  version: 0.1.0
  description: >-
    API template for exposing normalized food inspection data from the PrepChef Supabase instance.
servers:
  - url: https://api.prepchef.dev/v1
    description: Production
  - url: https://api-staging.prepchef.dev/v1
    description: Staging
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-prepchef-key
  schemas:
    Inspection:
      type: object
      required:
        - id
        - county_id
        - inspection_date
        - establishment_name
        - result
      properties:
        id:
          type: string
          format: uuid
        county_id:
          type: string
          format: uuid
        establishment_name:
          type: string
        establishment_address:
          type: string
          nullable: true
        inspection_date:
          type: string
          format: date
        inspection_type:
          type: string
          nullable: true
        inspection_score:
          type: number
          format: float
          nullable: true
        grade:
          type: string
          nullable: true
        result:
          type: string
        violation_count:
          type: integer
        violations:
          type: array
          items:
            type: object
        data_source_id:
          type: string
          format: uuid
        ingestion_run_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
paths:
  /inspections:
    get:
      summary: List inspections
      description: >-
        Retrieve normalized inspection records filtered by optional query parameters.
      security:
        - ApiKeyAuth: []
      parameters:
        - name: county_id
          in: query
          description: Filter by specific county UUID
          schema:
            type: string
            format: uuid
        - name: start_date
          in: query
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          schema:
            type: string
            format: date
        - name: min_score
          in: query
          schema:
            type: number
        - name: result
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 100
            maximum: 1000
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Inspection'
                  count:
                    type: integer
        '401':
          description: Unauthorized
        '500':
          description: Server error
  /inspections/{id}:
    get:
      summary: Get inspection by ID
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Inspection detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inspection'
        '404':
          description: Not found
