id: portland
display: "Portland (Multnomah County)"
state: OR
health_code: "Multnomah County Health Code Chapter 5"
health_dept_url: "https://multco.us/health/food-safety"
business_portal_url: "https://www.portlandoregon.gov/revenue/"

# Permit requirements
permit_kinds:
  - commissary
  - fire
  - ventilation
  - health_permit

# Insurance requirements
insurance:
  liability_min_cents: 100000000      # $1,000,000
  aggregate_min_cents: 200000000      # $2,000,000
  additional_insured_legal: "City of Portland and Multnomah County"
  workers_comp_required: true
  workers_comp_employee_threshold: 1

# Zoning
zoning:
  require_neighborhood_notice: false
  community_notification_required: true
  notification_period_days: 14

# Fees and taxes
fees:
  - code: Lodging
    display_name: "Multnomah County Lodging Tax"
    kind: percent
    value: 0.1150                     # 11.5%
    applies_to:
      - base
      - cleaning
      - platform_fee
    citation: "Multnomah County Code 12.600"
    remittance_url: "https://multco.us/file/39537/download"

# Security deposits
deposits:
  min_cents: 10000                    # $100 minimum
  hold_window_hours: 72
  refund_window_hours: 168            # 7 days

# Rental limits
rental_limits:
  max_hours_per_day_per_facility: 14
  min_booking_hours: 2
  max_advance_booking_days: 180

# Sound ordinance
sound_ordinance:
  quiet_hours:
    start: "22:00"
    end: "07:00"
  max_decibels_day: 60
  max_decibels_night: 50
  citation: "Portland City Code 18.10"

# Seasonal restrictions
seasonal_restrictions: []             # None currently for Portland

# Waste management
waste:
  requires_food_waste_recycling: true
  requires_composting: false
  citation: "Portland City Code 17.102"

# Inspection schedules
inspections:
  health:
    frequency_months: 12
    buffer_before_hours: 4
    buffer_after_hours: 2
  fire:
    frequency_months: 12
    buffer_before_hours: 2
    buffer_after_hours: 1

# Grease management
grease:
  interceptor_required: true
  max_service_interval_days: 90
  manifest_required: true

# Outbreak notification
outbreak:
  auto_notify_threshold: 3            # Auto-notify health dept if >= 3 illnesses
  notification_email: "foodborne.illness@multco.us"
  hotline: "503-988-3674"

# Complaint thresholds
complaints:
  noise:
    warning_threshold: 3              # 3 complaints in 30 days = warning
    window_days: 30
    soft_block_threshold: 5           # 5 complaints in 60 days = soft block
    soft_block_window_days: 60
