name: Post-Merge Validation
description: Run the post-merge operational validation checks
title: "Post-Merge Validation — <YYYY-MM-DD>"
labels: ["qa", "ops"]
body:
  - type: markdown
    attributes:
      value: |
        Run through each checklist and attach artifacts (screenshots, logs).
  - type: checkboxes
    id: functional
    attributes:
      label: Functional Verification
      options:
        - label: All tests green
        - label: Key endpoints manually verified
        - label: Stripe sandbox flow completes
        - label: DENY case verified
  - type: checkboxes
    id: infra
    attributes:
      label: Infrastructure Smoke Test
      options:
        - label: Staging boot ok
        - label: Grafana metrics flowing
        - label: Alerts wired
