image: ghcr.io/prep/optimizers:{{ .Chart.AppVersion }}
env:
  REDIS_URL: "redis://redis:6379"
  POLICY_URL: "http://policy:8081/policy/evaluate"
  RCS_URL: "http://control-plane:8080/rcs"
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "512Mi"
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
