openapi: 3.1.0
info:
  title: Prep City Compliance API
  version: 0.1.0
paths:
  /city/{city}/regulations:
    get:
      parameters:
        - name: city
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  jurisdiction: { type: string }
                  regulations:
                    type: array
                    items:
                      type: object
                      properties:
                        category: { type: string }
                        code: { type: string }
                        title: { type: string }
                        summary: { type: string }
                        source: { type: string }
                        url: { type: string, format: uri }
  /city/{city}/fees:
    get:
      summary: Get normalized fee schedule for a city
      parameters:
        - name: city
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required: [jurisdiction, paperwork, fees, totals, validation]
                properties:
                  jurisdiction: { type: string }
                  paperwork:
                    type: array
                    items: { type: string }
                  fees:
                    type: array
                    items:
                      type: object
                      required: [name, amount_cents, kind]
                      properties:
                        name: { type: string }
                        amount_cents: { type: integer, minimum: 0 }
                        kind: { type: string, enum: [one_time, recurring, incremental] }
                        cadence:
                          type: string
                          enum: [annual, semi_annual, quarterly, monthly, per_permit, per_inspection, per_application, per_reinspection]
                          nullable: true
                        unit: { type: string, nullable: true }
                        tier_min_inclusive: { type: integer, nullable: true }
                        tier_max_inclusive: { type: integer, nullable: true }
                  totals:
                    type: object
                    properties:
                      one_time_cents: { type: integer }
                      recurring_annualized_cents: { type: integer }
                      incremental_fee_count: { type: integer }
                  validation:
                    type: object
                    properties:
                      is_valid: { type: boolean }
                      issues:
                        type: array
                        items: { type: string }
        "404": { description: Unsupported city }
