id: seattle
display: "Seattle (King County)"
state: WA
health_code: "Seattle Municipal Code 10.10"
health_dept_url: "https://kingcounty.gov/depts/health/environmental-health/food-safety.aspx"
business_portal_url: "https://www.seattle.gov/licenses-and-permits"

# Permit requirements
permit_kinds:
  - TFE                               # Temporary Food Establishment
  - commissary
  - fire
  - ventilation
  - health_permit

# Insurance requirements
insurance:
  liability_min_cents: 100000000      # $1,000,000
  aggregate_min_cents: 200000000      # $2,000,000
  additional_insured_legal: "City of Seattle and King County"
  workers_comp_required: true
  workers_comp_employee_threshold: 1

# Zoning
zoning:
  require_neighborhood_notice: false
  community_notification_required: false

# Fees and taxes
fees:
  - code: KingCountyLodging
    display_name: "King County Lodging Tax"
    kind: percent
    value: 0.0200                     # 2%
    applies_to:
      - base
      - cleaning
    citation: "King County Code 6.27"
    remittance_url: "https://kingcounty.gov/depts/finance-business-operations/treasury/lodging-tax.aspx"
  - code: B&O
    display_name: "Seattle Business & Occupation Tax"
    kind: percent
    value: 0.0044                     # 0.44%
    applies_to:
      - platform_fee
    citation: "Seattle Municipal Code 5.45"
    remittance_url: "https://www.seattle.gov/licenses-and-permits/taxes-and-fees/business-license-tax"

# Security deposits
deposits:
  min_cents: 10000                    # $100 minimum
  hold_window_hours: 72
  refund_window_hours: 168            # 7 days

# Rental limits
rental_limits:
  max_hours_per_day_per_facility: 16
  min_booking_hours: 2
  max_advance_booking_days: 180

# Sound ordinance
sound_ordinance:
  quiet_hours:
    start: "22:00"
    end: "07:00"
  max_decibels_day: 70
  max_decibels_night: 55
  citation: "Seattle Municipal Code 25.08"

# Seasonal restrictions
seasonal_restrictions: []             # None currently for Seattle

# Waste management
waste:
  requires_food_waste_recycling: true
  requires_composting: false
  citation: "Seattle Municipal Code 21.36"

# Inspection schedules
inspections:
  health:
    frequency_months: 12
    buffer_before_hours: 4
    buffer_after_hours: 2
  fire:
    frequency_months: 12
    buffer_before_hours: 2
    buffer_after_hours: 1

# Grease management
grease:
  interceptor_required: true
  max_service_interval_days: 60       # More frequent in Seattle
  manifest_required: true

# Outbreak notification
outbreak:
  auto_notify_threshold: 3            # Auto-notify health dept if >= 3 illnesses
  notification_email: "food.safety@kingcounty.gov"
  hotline: "206-263-9566"

# Complaint thresholds
complaints:
  noise:
    warning_threshold: 3              # 3 complaints in 30 days = warning
    window_days: 30
    soft_block_threshold: 5           # 5 complaints in 60 days = soft block
    soft_block_window_days: 60
