#!/bin/bash
#
# Script to create GitHub issues from the identified codebase issues.
# This script uses the gh CLI to create issues in the repository.
#
# Usage:
#   ./scripts/create_github_issues_from_scan.sh
#
# Requirements:
#   - gh CLI installed and authenticated
#   - IDENTIFIED_ISSUES.json file generated by create_codebase_issues.py

set -e

REPO="PetrefiedThunder/Prep"
ISSUES_FILE="IDENTIFIED_ISSUES.json"

echo "=================================="
echo "GitHub Issue Creator"
echo "=================================="
echo ""

# Check if gh is authenticated
if ! gh auth status &> /dev/null; then
    echo "❌ Error: GitHub CLI is not authenticated"
    echo "Please run: gh auth login"
    exit 1
fi

# Check if issues file exists
if [ ! -f "$ISSUES_FILE" ]; then
    echo "❌ Error: $ISSUES_FILE not found"
    echo "Please run: python scripts/create_codebase_issues.py --dry-run"
    exit 1
fi

echo "✅ GitHub CLI authenticated"
echo "✅ Issues file found: $ISSUES_FILE"
echo ""

# Extract the number of issues
ISSUE_COUNT=$(python3 -c "import json; print(json.load(open('$ISSUES_FILE'))['total_issues'])")
echo "📝 Found $ISSUE_COUNT issues to create"
echo ""

# Confirm before creating
read -p "Do you want to create these $ISSUE_COUNT issues in $REPO? (y/N) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Aborted"
    exit 1
fi

echo ""
echo "Creating issues..."
echo ""

# Create issues using Python to parse JSON
python3 << 'EOF'
import json
import subprocess
import sys

# Load issues
with open("IDENTIFIED_ISSUES.json") as f:
    data = json.load(f)

issues = data["issues"]
created = 0
failed = 0

for i, issue in enumerate(issues, 1):
    title = issue["title"]
    body = issue["body"]
    labels = ",".join(issue["labels"])
    priority = issue["priority"]
    
    print(f"[{i}/{len(issues)}] Creating: {title}")
    
    # Add priority to body
    body_with_priority = f"**Priority:** {priority}\n\n{body}"
    
    try:
        # Create issue using gh CLI
        result = subprocess.run(
            [
                "gh", "issue", "create",
                "--repo", "PetrefiedThunder/Prep",
                "--title", title,
                "--body", body_with_priority,
                "--label", labels
            ],
            capture_output=True,
            text=True,
            check=True
        )
        
        # Extract issue URL from output
        issue_url = result.stdout.strip()
        print(f"  ✅ Created: {issue_url}")
        created += 1
        
    except subprocess.CalledProcessError as e:
        print(f"  ❌ Failed: {e.stderr}")
        failed += 1
    
    print("")

print("=" * 50)
print(f"Summary:")
print(f"  Created: {created}")
print(f"  Failed: {failed}")
print(f"  Total: {len(issues)}")
print("=" * 50)

sys.exit(0 if failed == 0 else 1)
EOF

echo ""
echo "✅ Done!"
echo ""
echo "View all issues: https://github.com/$REPO/issues"
