# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict, Field


class ErrorResponse(BaseModel):
    """Shared error envelope."""

    error: str = Field(description="Machine-readable error code.")
    message: str = Field(description="Human-readable error message.")
    details: Optional[Dict[str, Any]] = Field(
        default=None, description="Additional structured details about the failure."
    )

    model_config = ConfigDict(extra="allow")
