# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ErrorResponse(BaseModel):
    """Shared error envelope."""

    error: str = Field(description="Machine-readable error code.")
    message: str = Field(description="Human-readable error message.")
    details: dict[str, Any] | None = Field(
        default=None, description="Additional structured details about the failure."
    )

    model_config = ConfigDict(extra="allow")
