# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class Fee(BaseModel):
    """City fee definition."""

    id: str = Field(description="Unique fee identifier.")
    name: str = Field(description="Short human readable name for the fee.")
    description: Optional[str] = Field(default=None)
    amount: float = Field(description="Monetary amount in the provided currency.")
    currency: str = Field(description="ISO 4217 currency code.")
    frequency: Optional[str] = Field(
        default=None, description="How often the fee is due."
    )

    model_config = ConfigDict(extra="allow")
