# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from .fee import Fee


class FeeCollection(BaseModel):
    """Response payload for the fees listing."""

    city: str
    fees: list[Fee]
    business_type: str | None = Field(default=None, alias="businessType")

    model_config = ConfigDict(extra="allow", populate_by_name=True)
