# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from .fee import Fee


class FeeCollection(BaseModel):
    """Response payload for the fees listing."""

    city: str
    fees: List[Fee]
    business_type: Optional[str] = Field(default=None, alias="businessType")

    model_config = ConfigDict(extra="allow", populate_by_name=True)
