# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from .requirement_due_payload import RequirementDuePayload


class RequirementDueWebhook(BaseModel):
    """Envelope for requirement.due.soon events."""

    event: str = Field(description="Event name.")
    data: RequirementDuePayload

    model_config = ConfigDict(extra="allow")
