# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from .requirement import Requirement


class RequirementEstimateResponse(BaseModel):
    """Estimate output payload."""

    city: str
    currency: str
    total_estimated_fees: float = Field(alias="totalEstimatedFees")
    assumptions: list[str] | None = None
    requirements: list[Requirement]

    model_config = ConfigDict(extra="allow", populate_by_name=True)
