# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from .requirement_status_payload import RequirementStatusPayload


class RequirementStatusWebhook(BaseModel):
    """Envelope for requirement.status.updated events."""

    event: str = Field(description="Event name.")
    data: RequirementStatusPayload

    model_config = ConfigDict(extra="allow")
