# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from .requirement import Requirement


class RequirementCollection(BaseModel):
    """Collection of compliance requirements."""

    city: str
    requirements: List[Requirement]
    registration_status: Optional[str] = Field(default=None, alias="registrationStatus")

    model_config = ConfigDict(extra="allow", populate_by_name=True)
