# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class RequirementDuePayload(BaseModel):
    """Webhook payload for upcoming due date notifications."""

    id: str
    due_date: str = Field(alias="dueDate")
    city: str
    name: str | None = None
    days_until_due: int | None = Field(default=None, alias="daysUntilDue")

    model_config = ConfigDict(extra="allow", populate_by_name=True)
