# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Requirement(BaseModel):
    """Compliance requirement metadata."""

    id: str
    name: str
    description: str | None = None
    status: str
    due_date: str | None = Field(default=None, alias="dueDate")
    dependencies: list[str] | None = None

    model_config = ConfigDict(extra="allow", populate_by_name=True)
