# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class RequirementStatusPayload(BaseModel):
    """Webhook payload for requirement status changes."""

    id: str
    status: str
    occurred_at: str = Field(alias="occurredAt")
    city: str | None = None
    previous_status: str | None = Field(default=None, alias="previousStatus")

    model_config = ConfigDict(extra="allow", populate_by_name=True)
