# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from .requirement import Requirement


class RequirementEstimateResponse(BaseModel):
    """Estimate output payload."""

    city: str
    currency: str
    total_estimated_fees: float = Field(alias="totalEstimatedFees")
    assumptions: Optional[List[str]] = None
    requirements: List[Requirement]

    model_config = ConfigDict(extra="allow", populate_by_name=True)
