# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class Requirement(BaseModel):
    """Compliance requirement metadata."""

    id: str
    name: str
    description: Optional[str] = None
    status: str
    due_date: Optional[str] = Field(default=None, alias="dueDate")
    dependencies: Optional[List[str]] = None

    model_config = ConfigDict(extra="allow", populate_by_name=True)
