# This file was auto-generated by openapi-python-client.
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class RequirementEstimateRequest(BaseModel):
    """Request body for requirement estimates."""

    city: str = Field(description="City slug for the request.")
    business_type: str = Field(alias="businessType", description="Business classification used in estimating filings.")
    annual_revenue: Optional[float] = Field(default=None, alias="annualRevenue")
    employee_count: Optional[int] = Field(default=None, alias="employeeCount")
    filing_frequency_preference: Optional[str] = Field(default=None, alias="filingFrequencyPreference")

    model_config = ConfigDict(extra="allow", populate_by_name=True)
