name: Contract Tests

on:
  push:
    paths:
      - 'schemas/**'
      - 'apps/policy_engine/**'
      - 'apps/obligation_extractor/**'
  pull_request:

jobs:
  contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jsonschema
      - name: Validate obligation schema
        run: |
          python - <<'PY'
import json
from pathlib import Path
from jsonschema import Draft7Validator

schema = json.loads(Path('schemas/policy/obligation.schema.json').read_text())
Draft7Validator.check_schema(schema)
print('schema valid')
PY
