name: Post-Merge Validation
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      API: ${{ secrets.STAGING_API_BASE_URL }}
      AUTH: ${{ secrets.SEED_ADMIN_TOKEN }}
    steps:
      - name: Health checks
        run: |
          curl -fsS "$API/healthz"
          curl -fsS "$API/bookings/healthz" || true
          curl -fsS "$API/compliance/healthz" || true

      - name: Seed (idempotent)
        run: |
          curl -s -H "Authorization: Bearer $AUTH" -H "Content-Type: application/json" \
            -d @scripts/fixtures/seed_hosts.json "$API/onboarding/host/bulk" || true
          curl -s -H "Authorization: Bearer $AUTH" -H "Content-Type: application/json" \
            -d @scripts/fixtures/seed_makers.json "$API/onboarding/maker/bulk" || true

      - name: Compliance evaluate sample pair
        run: |
          MAKER_ID=$(curl -s "$API/debug/random_maker" | jq -r .maker_id)
          KITCHEN_ID=$(curl -s "$API/debug/random_kitchen" | jq -r .kitchen_id)
          curl -fsS -X POST "$API/compliance/evaluate" \
            -H "Authorization: Bearer $AUTH" -H "Content-Type: application/json" \
            -d "{\"maker_id\":\"$MAKER_ID\",\"kitchen_id\":\"$KITCHEN_ID\",\"date\":\"2025-11-05T10:00:00-08:00\"}"

      - name: Booking E2E (hold → confirm → payout scheduled)
        run: |
          MAKER_ID=$(curl -s "$API/debug/random_maker" | jq -r .maker_id)
          KITCHEN_ID=$(curl -s "$API/debug/random_kitchen" | jq -r .kitchen_id)
          B=$(curl -s -X POST "$API/bookings" \
            -H "Authorization: Bearer $AUTH" -H "Content-Type: application/json" \
            -d "{\"maker_id\":\"$MAKER_ID\",\"kitchen_id\":\"$KITCHEN_ID\",\"start\":\"2025-11-05T10:00:00-08:00\",\"end\":\"2025-11-05T12:00:00-08:00\",\"deposit_cents\":10000,\"quote\":{\"hourly_cents\":5500,\"hours\":2,\"cleaning_cents\":1500,\"platform_fee_bps\":1000}}")
          BOOKING_ID=$(echo "$B" | jq -r .booking_id)
          curl -fsS -X POST "$API/bookings/$BOOKING_ID/confirm" -H "Authorization: Bearer $AUTH"

      - name: Webhook idempotency (replay 10x → 1 row)
        env:
          SIGSECRET: ${{ secrets.PREP_WEBHOOK_SECRET }}
        run: |
          PAYLOAD='{"id":"evt_ci_fixed","type":"charge.succeeded","data":{"object":{"id":"pi_ci"}}}'
          SIG=$(printf "%s" "$PAYLOAD$SIGSECRET" | sha256sum | awk '{print $1}')
          for i in $(seq 1 10); do
            curl -s -X POST "$API/payments/webhook/stripe" \
              -H "Stripe-Signature: t=12345,v1=$SIG" -H "Content-Type: application/json" \
              -d "$PAYLOAD" >/dev/null
          done
          curl -fsS "$API/debug/webhook_count?event_id=evt_ci_fixed" | jq
